### ISSUE TITLE
Problem with creating supplemental policy

### ISSUE THREAD

**Issue by Stuart-McGuire** [MicrosoftDocs/WDAC-Toolkit#362] opened 2024-04-15 21:37 UTC
In our environment we have fairly locked down endpoints and something appears to be getting in the way of WDAC Wizard creating supplemental policies (it seems to be able to create base policies fine). Can anybody point me in the right direction as to what might be causing the snag? A copy of the log file is below.

2024-04-15T21-30-14 [INFO]: WDAC Policy Wizard Version # 2.4.2.0
2024-04-15T21-30-14 [INFO]: Session ID: 133576802912070942
2024-04-15T21-30-15 [INFO]: **********************************************************************
2024-04-15T21-30-15 [INFO]: Workflow -- New Policy Selected
2024-04-15T21-30-15 [INFO]: **********************************************************************
2024-04-15T21-30-15 [INFO]: ==== Policy Type Page Initialized ====
2024-04-15T21-30-15 [INFO]: Setting WDAC Policy Format to MultiPolicy
2024-04-15T21-30-20 [INFO]: New supplemental policy flow. Valid policy ID entered: 
2024-04-15T21-30-25 [INFO]: ==== Configuration Template Page Initialized ====
2024-04-15T21-30-25 [INFO]: --- Reading Set Rules from C:\Program Files\WindowsApps\Microsoft.WDAC.WDACWizard_2.4.2.0_x64__8wekyb3d8bbwe\Empty_Supplemental.xml ---
2024-04-15T21-30-27 [INFO]: ==== Signing Rules Page Initialized ====
2024-04-15T21-30-27 [INFO]: --- Reading Set Signing Rules Beginning ---
2024-04-15T21-30-27 [INFO]: Reading file rules from path: C:\Program Files\WindowsApps\Microsoft.WDAC.WDACWizard_2.4.2.0_x64__8wekyb3d8bbwe\Empty_Supplemental.xml
2024-04-15T21-30-28 [INFO]: ==== Custom Signing Rules Panel Initialized ====
2024-04-15T21-30-28 [INFO]: Rule Permission set to Allow
2024-04-15T21-30-28 [INFO]: --- Create Custom Rules Selected ---
2024-04-15T21-30-35 [INFO]: Custom File Rule Level Set to Publisher
2024-04-15T21-30-42 [INFO]: --- New Custom Rule Added ---
2024-04-15T21-30-42 [INFO]: CUSTOM RULE Created: Allow - Publisher - CA: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US & CN: CN=Zebra Technologies Corporation, O=Zebra Technologies Corporation, L=Lincolnshire, S=Illinois, C=US & Filename: CardStudio-Setup_2.5.23.exe & Min Version: 2.5.23.0 -  
2024-04-15T21-30-44 [INFO]: **********************************************************************
2024-04-15T21-30-44 [INFO]: Workflow -- Building Policy Underway
2024-04-15T21-30-44 [INFO]: **********************************************************************
2024-04-15T21-30-45 [INFO]: --- Merge Custom Rules Policy ---
2024-04-15T21-30-45 [INFO]: --- Merge Templates Policy ---
2024-04-15T21-30-45 [ERROR]: MergeTemplatesPolicy() encountered the following error: Unable to locate any policies to merge
2024-04-15T21-30-45 [INFO]: Running the following Merge Commands: 
2024-04-15T21-30-45 [INFO]: Merge-CIPolicy -PolicyPaths -OutputFilePath "C:\Users\my username\Documents\Supplemental_Policy2024-04-15_2.xml"
2024-04-15T21-30-45 [ERROR]: Exception encountered in MergeTemplatesPolicy(): System.Management.Automation.ParameterBindingException: Missing an argument for parameter 'PolicyPaths'. Specify a parameter of type 'System.String[]' and try again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at WDAC_Wizard.MainWindow.MergeTemplatesPolicy(String customRulesMergePath, BackgroundWorker worker)
2024-04-15T21-30-45 [INFO]: --- Create Policy Rule Options --- 
2024-04-15T21-30-45 [INFO]: -- Set Additional Parameters --
2024-04-15T21-30-45 [INFO]: **********************************************************************
2024-04-15T21-30-45 [INFO]: Workflow -- DONE
2024-04-15T21-30-45 [INFO]: **********************************************************************

Kind Regards
Stuart

**Comment by jgeurten** [comment] 2024-04-17 18:44
Hi @Stuart-McGuire, I think I see the problem. I encounter the same issue if I don't specify the correct Rule Scope. For instance, if I leave Kernel Rule for FirefoxInstaller.exe, a rule is not generated (because the Wizard detects it's not a driver). 

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/75de5ee0-8c47-42c9-844b-6dbea4bb02cf)


If you set the Rule Scope to **Usermode**, does this fix your issue?

**Comment by jgeurten** [comment] 2024-04-17 19:44
Seems to be related to this PowerShell but:  
![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/0aa6a733-54cc-48d1-b834-5094f2881a16)

**Comment by HotCakeX** [comment] 2024-04-18 17:45
> Seems to be related to this PowerShell bug: ![image](https://private-user-images.githubusercontent.com/23045608/323358078-0aa6a733-54cc-48d1-b834-5094f2881a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjI1MDYsIm5iZiI6MTcxMzQ2MjIwNiwicGF0aCI6Ii8yMzA0NTYwOC8zMjMzNTgwNzgtMGFhNmE3MzMtNTRjYy00OGQxLWI4MzQtNTA5NGYyODgxYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE3NDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODRmYmEwNWVlODliOGJhNWQ2NWYyYzQyYTA1MmIwNGU0ZjNiN2MwZTU3ODhkNzgyZGYzMjEwMTIwNTIzODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RMXxqxC_JiR0diyCIvvaaU8cxe4w6iA_4kELcCoKqc)

Yes! I'm kinda glad someone else can reproduce it too now, I always thought it's got something to do with my hardware only

Related issue: https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/302

**Comment by HotCakeX** [comment] 2024-04-18 17:50
This is the new version of that error btw

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/118815227/f6075244-eaba-41f3-aaa8-6343d8888fbd)

So far I know that it can be fixed by stopping the cmdlet and running the same exact command again in the same session. So the error only shows up once in each PowerShell session and any subsequent invocation of the ConfigCI cmdlets will run just fine.

**Comment by jgeurten** [comment] 2024-04-19 15:30
I think I will play around with creating a dummy PowerShell session to frontload this error so subsequent commands pass. We're looking at fixing and servicing the PowerShell bug but it will still take time to saturate the ecosystem so I think this is the safest thing to do in the meantime.

**Closed** 2024-05-02 16:58 UTC
