### ISSUE TITLE
WHQL Required

### ISSUE THREAD

**Issue by TCGL23** [MicrosoftDocs/WDAC-Toolkit#268] opened 2023-07-26 14:34 UTC
If using Default or Signed and Reputable Mode WHQL appears to be set to Required and the wizard does not show this in the policy rule screen as highlighted but is set in the policy rule

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/140627881/51f3d90c-a191-4d85-b868-dcd070d5b44f)

    <Rule>
      <Option>Required:WHQL</Option>

where using Allow Microsoft mode Require WHQL is not enabled unless you switch on the policy rule

all three options appear to show this should be enabled across all three but not seeing this in the exports

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/140627881/d924e636-1d3c-4d37-9bb5-a0fb6f3a1ac1)

**Comment by jgeurten** [comment] 2023-07-31 17:46
Hi @TCGL23, can you confirm the version of the Wizard you are using. I cannot reproduce this issue on the latest version 2.3.1.1. 

None of the templates, Windows, Allow Microsoft or Signed and Reputable mode set the "Require WHQL" policy option.

**Comment by jgeurten** [comment] 2023-08-04 16:58
Closing issue as I am not able to reproduce this on any of the template versions.

**Closed** 2023-08-04 16:58 UTC
