### ISSUE TITLE
Policy Editor isn't applying the changes to the policy file

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#212] opened 2023-02-19 19:31 UTC
Using Policy Editor => Edit Policy XML file => Browse for the current Policy XML file => Click next without doing anything else => in Policy Rules section change something like turn Audit Mode on or off => Next page check the 2 boxes for recommended block lists => the build shows 100% successful but no change is made to the file.

WDAC Wizard Version 2.2.0.0

**Comment by jgeurten** [comment] 2023-02-22 01:55
This one I cannot reproduce. The Wizard creates the proper xml when I turn on or off something on the rules page and configure the recommended blocks. 

The Wizard will not overwrite the existing policy by default. Instead, it creates a new policy xml file with <existing_file_name>_v10.0.0.1.xml or replace "10.0.0.1" with vNext of your existing xml

**Comment by HotCakeX** [comment] 2023-02-22 08:47
> This one I cannot reproduce. The Wizard creates the proper xml when I turn on or off something on the rules page and configure the recommended blocks.
> 
> The Wizard will not overwrite the existing policy by default. Instead, it creates a new policy xml file with <existing_file_name>_v10.0.0.1.xml or replace "10.0.0.1" with vNext of your existing xml

Hi, you're right, sorry, I thought since I didn't specify a new save location, the wizard would just make the changes to the same file I selected but now I notice it creates the files in the Documents folder instead.

So definitely not an issue but may I suggest saving the new file in the same directory as the policy file we try to edit, with a different name?

**Comment by jgeurten** [comment] 2023-02-23 00:23
> So definitely not an issue but may I suggest saving the new file in the same directory as the policy file we try to edit, with a different name? This way the original policy file won't be overwritten and also the new files will be saved in an expected location.

This is how the Wizard works today. If you do not specify the path to save the new policy, it will save the file in the same directory as the original policy unless the original directory is not user-writable, in which case its saved to the documents folder by default.

**Comment by HotCakeX** [comment] 2023-02-23 09:17
> > So definitely not an issue but may I suggest saving the new file in the same directory as the policy file we try to edit, with a different name? This way the original policy file won't be overwritten and also the new files will be saved in an expected location.
> 
> This is how the Wizard works today. If you do not specify the path to save the new policy, it will save the file in the same directory as the original policy unless the original directory is not user-writable, in which case its saved to the documents folder by default.


Well, that's the thing, it doesn't work like that. I put the policy I want to edit on my desktop. I even disabled controlled folder access to make sure desktop folder isn't protected, not that I was getting any blocked notifications, but just to make sure, and still, when I edit the policy file on my desktop, the wizard saves the new policy on the documents folder.


Not sure if it's related but when I try to reset Wizard settings, I keep getting this error:

![image](https://user-images.githubusercontent.com/118815227/220865620-c9b0026c-e14c-4245-9f76-3829731821dc.png)

**Comment by HotCakeX** [comment] 2023-02-23 09:48
Just made a quick video of how to reproduce it. this time tried it on a VM.

https://1drv.ms/v/s!AtCaUNAJbbvIhtFhZGpxfqBIRBBgEQ?e=98pjj5

**Comment by jgeurten** [comment] 2023-02-24 22:59
Hmm, I see what you mean - thanks for putting that together. I can't repro on any of my machines for some reason but I also don't think its the worst behavior in the world. I mean, the Wizard spells out exactly where the files are located. Worst case scenario is someone needs to copy the file into a different directory. I am going to politely close this bug out as won't fix.

**Closed by jgeurten** 2023-02-24 22:59 UTC
Labels: question
