### ISSUE TITLE
Policy Creation Fails when using custom rules

### ISSUE THREAD

**Issue by jdotmac** [MicrosoftDocs/WDAC-Toolkit#8] opened 2020-05-29 15:06 UTC
Building a new base policy stalls/fails on my machine (win10 2004) when adding custom allow rules (path based)

Error During Build
Output location:
Unable to locate

**Comment by jdotmac** [comment] 2020-05-29 19:22
Also it appears when building a base policy with custom deny rules (fileName) these are written as Allow rules in the XML

**Comment by jgeurten** [comment] 2020-06-07 18:16
Hi @jdotmac, sorry about the failure. Can you please try the latest version (1.5.5) to see if it resolves your build problem? Please let me know the result.

**Comment by WildByDesign** [comment] 2020-11-10 00:19
This issue is still occurring on latest 1.6.0 release.

**Cause:** Any _directories which have a space_ (eg. C:\Program Files, C:\Program Files (x86), D:\test test, etc.)

**Reproduce:** Create a file path rule and choose a directory which contains a space based on Folder option. (choosing File option with directory containing space works correctly).

**Error:** There was an error building your policy. Press home to begin again.
Output location:
Unable to locate

**Comment by jgeurten** [comment] 2020-11-10 02:01
@jdotmac, @WildByDesign  cc @jsuther1974 
addressed this issue in PR #15. Thank you for bringing this to my attention. I should have the update online by tomorrow. 

Thanks, Jordan

**Comment by WildByDesign** [comment] 2020-11-13 15:45
@jgeurten Thank you for the quick fix. Could you please let us know when the updated binary is available online?

I haven't had any luck compiling WDAC-Toolkit myself yet because all attempts keep failing for me. Cheers!

**Comment by jgeurten** [comment] 2020-11-13 20:30
> @jgeurten Thank you for the quick fix. Could you please let us know when the updated binary is available online?

@WildByDesign @jdotmac version 1.6.1 is available online at https://webapp-wdac-wizard.azurewebsites.net. Existing versions will check for the 1.6.1. update automatically every 24 hours using MSIX technology. 

Thanks again for bringing this to my attention. Thanks for using the WDAC Wizard!

Closing the issue.

**Closed** 2020-11-13 20:30 UTC
