### ISSUE TITLE
Editing supplemental rules doesnt change the new file.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/WDAC-Toolkit#325] opened 2023-11-16 01:35 UTC
Using version 2.4.0.0 I edit a supplemental rule (I remove a rule from the policy), the new version of the file saves with the filename containing the incremental version number.

However I see the original file is edited and the incremental version file is not.

**Comment by cgerke** [comment] 2023-11-21 10:06
Sorry didn't see #296 

This looks like a duplicate.

**Comment by jgeurten** [comment] 2024-03-15 21:36
Thanks for reporting. You're right, looks like a dupe of #296. Thanks

**Closed by jgeurten** 2024-03-15 21:36 UTC
