### ISSUE TITLE
Remove Rule during policy editing not working

### ISSUE THREAD

**Issue by AlzheimerZA** [MicrosoftDocs/WDAC-Toolkit#319] opened 2023-10-24 04:36 UTC
During policy editing, you select the "Remove Rule" and the rule is removed from the GUI and the file is saved, but looking at the XML the rule is not removed.

**Comment by jgeurten** [comment] 2023-10-24 17:55
Can you please share examples of rules that are not removed from your XML

**Comment by AlzheimerZA** [comment] 2023-10-25 03:57
This seems to go hand in hand with the issue "Policy XML file retains previously removed file rules"
Removing any rule type from an existing XML file is not removed from the new version created, but instead is removed from the previous version. 
As example you would edit Base_v10.0.0.1.xml and remove rules and the tool creates a new file Base_v10.0.0.2.xml. 
File Base_v10.0.0.2.xml still has the removed rules within the xml, but Base_v10.0.0.1.xml will not have the rules.

**Comment by jgeurten** [comment] 2023-11-10 18:25
Duplicate of #296

**Closed by jgeurten** 2023-11-10 18:25 UTC
Labels: bug
