### ISSUE TITLE
can WDAC wizard prompts notification when user try to add hash rule for non-binary? 

### ISSUE THREAD

**Issue by celiajiang** [MicrosoftDocs/WDAC-Toolkit#299] opened 2023-09-27 05:27 UTC
when user try to add hash rule for non-binary，whether wizard can abort the policy file generation or at least display an error on screen stating that the hash file rule cannot be added?

For allow rule creation, I found that hash rule for the .cs file cannot be added.
 
Step to reproduce the problem (with [2.3.1.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__http%3A%2F2.3.1.1__%3B!!LSAcJDlP!1xPFVzd0BrN1ivYjfdRFfNuVsSU4ZNIfg3VYDsUVSiAymsvfYAHo0Wy-P15crw3yWsf6nqHO7D7FBrJ1C1ZVULcS3Yc%24&data=05%7C01%7CZixuan.Jiang%40microsoft.com%7C3ddb3ce78df944e7baa508dbbea844d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638313402188759548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DVk5QffNhSFk6B%2FpXTOU6Vb8M2wrwfnabVxX0dM%2BznI%3D&reserved=0))
1.	Edit an existing policy
2.	Click Add Custom Rule
3.	Select Rule Type => File Hash 
4.	Select Reference File => Change to All files (*.*) => Select the blocked .CS file
5.	Click Create Rule
6.	Click Next
7.	It looks like the policy is updated successfully.   The .xml and .cip are created.
 
8.	However, if the .xml is edited, hash rule is actually not added.
9.	Error is found in the wdacwizard log file.
2023-09-22T08-30-45 [INFO]: Workflow -- Edit Policy Selected
2023-09-22T08-30-45 [INFO]: **********************************************************************
2023-09-22T08-30-45 [INFO]: ==== Edit Workflow Page Initialized ====
2023-09-22T08-30-45 [INFO]: Browsing for existing WDAC Policy on file.
2023-09-22T08-30-52 [ERROR]: ParsePolicy encountered the following error messageSystem.NullReferenceException: Object reference not set to an instance of an object.
   at WDAC_Wizard.EditWorkflow.ParsePolicy(String xmlPath)
2023-09-22T08-30-52 [ERROR]: EditWorkflow Browse() encountered the following error : System.NullReferenceException: Object reference not set to an instance of an object.
   at WDAC_Wizard.EditWorkflow.DisplayPolicyInfo()
   at WDAC_Wizard.EditWorkflow.BrowseButton_Click(Object sender, EventArgs e)
2023-09-22T08-30-55 [INFO]: Browsing for existing WDAC Policy on file.
2023-09-22T08-31-02 [INFO]: ==== Configuration Template Page Initialized ====
2023-09-22T08-31-02 [INFO]: --- Reading Set Rules from Z:\HSBC-WDAC_TRPOC_BASE-v0_1__v10.0.0.8.xml ---

**Comment by HotCakeX** [comment] 2023-10-07 12:28
Seems like a duplicate of this one: https://github.com/MicrosoftDocs/WDAC-Toolkit/issues/297
The comments there should answer your question.

**Comment by celiajiang** [comment] 2023-10-10 04:04
> Seems like a duplicate of this one: #297 The comments there should answer your question.

Thanks. This intends to request a notification/error prompts window in wizard to notify the error instead of letting it move on and eventually unable to create any rule for non-binaries.

**Comment by jgeurten** [comment] 2023-11-10 18:23
I think it would be too challenging to implement this and I am not sold on the value.

**Closed by jgeurten** 2023-11-10 18:23 UTC
