### ISSUE TITLE
 MDE Advanced Hunting WDAC events parsing

### ISSUE THREAD

**Issue by wdacwizard** [MicrosoftDocs/WDAC-Toolkit#200] opened 2023-02-08 15:36 UTC
I am not sure if this is a bug or I misunderstood ISG. 

WDAC cannot parse the ISG action type: AppControlCodeIntegrityOriginAudited (3091). We use self-developed software which is distributed only in our company. It may be useful to allow such programs by a parsed MDE Rule.

It would certainly make sense to allow such 3rd party apps based on the MDE Adv. Hunting logs. The analysis via Advanced Hunting is much easier than to parse local log files.

**Comment by jgeurten** [comment] 2023-02-10 18:23
3091 events indicate that the file that was audited did not have reputation from ISG or Managed Installer. There will, however, still be 3076 events indicating that this same file was audited by WDAC. 

3091 events contain the following:

- Filename
- NTStatus
- ManagedInstallerEnabled bool
- PassesManagedInstaller bool
- SmartlockerEnabled bool
- PassesSmartlocker bool
- DefenderTrust bool
- AuditEnabled bool
- PolicyName
- PolicyID

None of these can be used in a WDAC policy rule. You can however use the 3076/3077 event fields to create a rule, which the Wizard supports.

**Comment by jgeurten** [comment] 2023-02-10 18:23
Closing as by design

**Closed** 2023-02-10 18:23 UTC
