### ISSUE TITLE
Editing Supplemental Policy converts it to a base policy

### ISSUE THREAD

**Issue by SeniorFeet** [MicrosoftDocs/WDAC-Toolkit#46] opened 2021-04-06 12:09 UTC
When editing an existing supplemental policy, upon saving it converts the policy to a base policy.

**Comment by jgeurten** [comment] 2021-04-06 21:30
This is also related to issue #44 and is addressed by PR #39. tl;dr the policy type was not being set upon initial import of the policy

**Comment by jgeurten** [comment] 2021-04-07 19:50
The issue is observed on latest build 1.6.3.0. during supplemental policy edit and specifying at least one file rule.

**Comment by jgeurten** [comment] 2022-02-18 21:42
Fixed in #67

**Closed by jgeurten** 2022-02-18 21:42 UTC
Labels: bug
