### ISSUE TITLE
Exception Rules Not Working

### ISSUE THREAD

**Issue by WildByDesign** [MicrosoftDocs/WDAC-Toolkit#54] opened 2021-08-02 14:49 UTC
I am using the latest version 1.6.4. I understand that with version 1.6.3, you have added the ability to create file rule exceptions. I just finally got a chance to start playing around with those rules now. 

However, I have tried about a dozen different combinations of file rule exceptions to try within the UI but none of the exceptions survive through to the XML output. The rules all show in the UI, but the XML file output only ever shows the base rule without any of the exceptions. I've tried almost all possibilities in the UI regarding exceptions and they all unfortunately fail to get to the XML.

The UI for custom rules (including exceptions) is fantastic, by the way.

On a side note, is there any Microsoft documentation for how to manually create these exception rules? Example XML structures to follow?

Thank you.

**EDIT:** While the bug still remains, I just found the answer to my question about manually creating WDAC exception rules and I will share it here just in case anyone else finds it beneficial. The manual method with exceptions can be used for now until the bug within the WDAC Wizard app is fixed. 

Link: https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2365

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/configci/New-CIPolicy.md#example-4-create-a-policy-with-exception-rules

and 

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/configci/New-CIPolicy.md#example-4-create-a-policy-with-exception-rules

**Comment by jgeurten** [comment] 2021-08-03 21:17
The latest version of the app, 1.6.4., does expose the ability to create rule exceptions. I have attached a photo of the experience. The rule says trust the DigiCert SHA2.. CA but not any file with product name=Notepad++. Clicking on "Add Exception" will append the exception to the local table after which "Create Rule" will add the rule+exception to the global table.

Ex. of the XML that it outputs. You should see the deny rules in the signing scenarios section

<FileRules>
    <Deny ID="ID_DENY_D_1_0_0" FriendlyName="C:\Users\<user>\Downloads\npp.7.9.5.Installer.x64.exe FileRule" ProductName="Notepad++" />
</FileRules>


<Signer ID="ID_SIGNER_S_1_0_0" Name="DigiCert SHA2 Assured ID Code Signing CA">
      <CertRoot Type="TBS" Value="E767799478F64A34B3F53FF3BB9057FE1768F4AB178041B0DCC0FF1E210CBA65" />
    </Signer>

<AllowedSigner SignerId="ID_SIGNER_S_1_0_0">
   <ExceptDenyRule DenyRuleID="ID_DENY_D_1_0_0" />
</AllowedSigner>



As for how to create the exceptions, it takes some Powershell scripting and CI schema knowledge so I do recommend using the Wizard but I documented the steps here: New-CIPolicy (ConfigCI) | Microsoft Docs<https://docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps#example-4--create-a-policy-with-exception-rules>.

Please let me know if I have answered your questions.

[cid:8fc0e12d-d6cd-4f6d-8aae-37227a9b202d]


Thanks,
Jordan
________________________________
From: WildByDesign ***@***.***>
Sent: Monday, August 2, 2021 7:49 AM
To: MicrosoftDocs/WDAC-Toolkit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/WDAC-Toolkit] Exception Rules Not Working (#54)


I am using the latest version 1.6.4. I understand that with version 1.6.3, you have added the ability to create file rule exceptions. I just finally got a chance to start playing around with those rules now.

However, I have tried about a dozen different combinations of file rule exceptions to try within the UI but none of the exceptions survive through to the XML output. The rules all show in the UI, but the XML file output only ever shows the base rule without any of the exceptions. I've tried almost all possibilities in the UI regarding exceptions and they all unfortunately fail to get to the XML.

The UI for custom rules (including exceptions) is fantastic, by the way.

On a side note, is there any Microsoft documentation for how to manually create these exception rules? Example XML structures to follow?

Thank you.

**Comment by WildByDesign** [comment] 2021-08-04 15:04
@jgeurten Thank you for taking the time and for the thorough response. Your XML output also helped to give me a good idea of the structure of the exceptions.

I had the wrong impression of how the exceptions worked. I tried to read as much MS documentation as possible but it was very limited when it came to exceptions. I was trying to do FileName rules with FilePath exceptions and different variations of those.

I ended up finding the best details by searching Github for WDAC exceptions, in particular, and the best details I found within code comments. 

My understanding now is that WDAC exceptions can only be applied to Signer rules. Is this correct?

If yes, it would be good if the WDAC Wizard would grey-out the Exceptions area of the custom rules section so that the user is blocked from creating rules that would not work. The back-end rule parsing works correctly in that it did not allow these rules to go through to the output XML. However, the UI does not give any indication of failure or let the user know that WDAC exceptions only work with Signer rules.

Cheers! I appreciate everything that you do with WDAC Wizard.

**Comment by jgeurten** [comment] 2021-08-09 16:23
@WildByDesign rule exceptions can be applied to any rules except file hash rules. Signer rules cannot except signer rules too.

**Comment by WildByDesign** [comment] 2021-08-10 14:10
Thank you for confirming that rule exceptions can be applied to any rules with the exception of file hash rules and the exception of signer rule exceptions on signer rules. I appreciate that. I have some more questions about that later but I want to make sure I provide good details along with those questions.

But for now, I do want to bring attention to a bug in the Rule Exceptions section of the Custom Rules dialog. It is possible that this bug might be affecting the outcome of what I am trying to do.

**Bug Location:** 

_Custom Rules dialog - Rule Exceptions - Exception Type: FilePath_

**Bug Details:** 

When choosing the Reference File in this section of the UI for FilePath, when you check the button for Folder and click Browse, it incorrectly brings up the dialog for selecting executables (All Binary Files). It should bring up the Browse For Folder dialog.

**Comment by jgeurten** [comment] 2022-03-24 04:20
Path rules cannot be excepted either. I updated the Wizard flow to reflect this. Closing this bug as by design.

**Closed by jgeurten** 2022-03-24 04:20 UTC
Labels: wontfix
